const TYPES=['Bill','Note','Bond','TIPS','FRN','CMB'];
const SNAPSHOT_URL='data/treasury.json';
const state={upcoming:[],recent:[],types:new Set(TYPES),deferredPrompt:null};
const $=id=>document.getElementById(id);
const fmtMoney=n=>Number(n||0).toLocaleString(undefined,{style:'currency',currency:'USD',maximumFractionDigits:2});
const fmtDate=v=>v?new Date(v+'T00:00:00').toLocaleDateString():'—';
const clean=v=>(v===null||v===undefined||v==='')?'—':String(v);
function typeOf(r){return r.security_type_desc||r.security_type||r.security_type_description||r.type||'Unknown'}
function dateOf(r){return r.auction_date||r.announcemt_date||r.issue_date||r.record_date||''}
function priceOf(r){for(const k of ['average_price','price_per100','price_per_100','high_price','low_price']){const n=parseFloat(r[k]);if(Number.isFinite(n)&&n>0)return n}return 100}
function withinLookback(r){const d=dateOf(r);if(!d)return true;const days=parseInt($('lookback').value,10);return new Date(d)>=new Date(Date.now()-days*86400000)}
function pass(r){const t=typeOf(r);return [...state.types].some(x=>t.toLowerCase().includes(x.toLowerCase()))}
function card(r,mode){const price=priceOf(r);const face=Math.floor(Number($('amount').value||0)/(price/100)/100)*100;const rate=r.high_investment_rate||r.high_discount_rate||r.interest_rate||r.coupon_rate||r.high_yield||r.avg_med_discnt_rate||'—';return '<article class="card"><span class="pill">'+clean(typeOf(r))+'</span><h3>'+clean(r.security_term||r.security_term_week_year||r.term||r.security_description||'Treasury security')+'</h3><div class="meta"><div><span>Auction date</span><strong>'+fmtDate(dateOf(r))+'</strong></div><div><span>Issue date</span><strong>'+fmtDate(r.issue_date)+'</strong></div><div><span>Rate / yield</span><strong>'+clean(rate)+'</strong></div><div><span>Maturity</span><strong>'+fmtDate(r.maturity_date)+'</strong></div>'+(mode==='planner'?'<div><span>Modeled price</span><strong class="price">'+price.toFixed(3)+' / 100</strong></div><div><span>Max face</span><strong>'+fmtMoney(face)+'</strong></div>':'')+'</div><p class="small">CUSIP: '+clean(r.cusip)+'</p></article>'}
function draw(){const upcoming=state.upcoming.filter(pass);const recent=state.recent.filter(r=>pass(r)&&withinLookback(r));$('upcomingCount').textContent=upcoming.length;$('recentCount').textContent=recent.length;$('modeledCash').textContent=fmtMoney($('amount').value||0);$('upcomingCards').innerHTML=upcoming.length?upcoming.map(r=>card(r,'upcoming')).join(''):'<article class="card">No matching upcoming auctions found.</article>';$('recentCards').innerHTML=recent.length?recent.map(r=>card(r,'recent')).join(''):'<article class="card">No matching recent auction results found.</article>';const base=upcoming.length?upcoming:recent;$('plannerCards').innerHTML=base.length?base.map(r=>card(r,'planner')).join(''):'<article class="card">Run the data refresh workflow to populate the planner.</article>'}
function msg(text){$('message').textContent=text;$('message').classList.toggle('hidden',!text)}
async function fetchAll(){msg('Loading Treasury data snapshot...');try{const response=await fetch(SNAPSHOT_URL+'?t='+Date.now(),{cache:'no-store'});if(!response.ok)throw new Error('Snapshot request returned '+response.status);const snapshot=await response.json();state.upcoming=snapshot.upcoming||[];state.recent=snapshot.recent||[];$('lastUpdated').textContent=snapshot.updated_at?'Treasury snapshot updated: '+new Date(snapshot.updated_at).toLocaleString():'Treasury snapshot loaded.';msg((state.upcoming.length||state.recent.length)?'':'Snapshot is empty. Run the Refresh Treasury Data workflow once.');draw()}catch(e){msg('Could not load data/treasury.json. Run the Refresh Treasury Data GitHub Action, then reload. '+e.message);draw()}}
function setup(){const chips=$('chips');TYPES.forEach(t=>{const b=document.createElement('button');b.className='chip active';b.type='button';b.textContent=t;b.onclick=()=>{state.types.has(t)?state.types.delete(t):state.types.add(t);b.classList.toggle('active');draw()};chips.appendChild(b)});document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')});$('refresh').onclick=fetchAll;$('amount').oninput=draw;$('lookback').onchange=draw;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredPrompt=e;$('installButton').classList.remove('hidden')});$('installButton').onclick=async()=>{if(!state.deferredPrompt)return;state.deferredPrompt.prompt();state.deferredPrompt=null;$('installButton').classList.add('hidden')};if('serviceWorker' in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});fetchAll()}
setup();
